version: '3.8'
services:
  mysql:
    container_name: DB
    image: mysql:8.0.17
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: SuperTajneHaslo
      MYSQL_DATABASE: DB
    ports:
      - "3306:3306"
    volumes:
      - "./DB:/docker-entrypoint-initdb.d/DB.sql"

  admin:    
    image: adminer    
    restart: always
    ports:      
      - "8080:8080"

  client1:
    build:
      context: ./Client
      args:
        OPEN_PORT: 5000
    restart: always
    environment:
      SERVER_PORT: 6060
    ports:      
      - "5000:5000"


  server:
    build:
      context: ./Server
      args:
        OPEN_PORT: 6060
    restart: always
    environment:
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: SuperTajneHaslo
      MYSQL_DATABASE_DB: DB
      MYSQL_DATABASE_HOST: DB
      MYSQL_DATABASE_PORT: 3306
    ports:      
      - "6060:6060"
      


