version: '3.8'
services:
  mysql:
    container_name: DB
    image: mysql:8.0.17
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: SuperTajneHaslo
      MYSQL_DATABASE: DB
    ports:
      - "3306:3306"
    volumes:
      - "./db/baza.sql:/docker-entrypoint-initdb.d/1.sql"
  admin:    
    image: adminer    
    restart: always
    ports:      
      - "8080:8080"

