version: '3.8'
services:
  mysql:
    container_name: DB
    image: mysql:8.0.17
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/DB.sql
    environment:
      MYSQL_ROOT_PASSWORD: SuperTajneHaslo
      MYSQL_DATABASE: DB
    ports: ['${DB_PORT}:${DB_PORT}']
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./DB/DB.sql:/docker-entrypoint-initdb.d/DB.sql"

   
       
  admin:    
    image: adminer
    restart: always
    ports: ['${ADMINER_PORT}:${ADMINER_PORT}']

  client1:
    build:
      context: ./Client
      args:
        OPEN_PORT: ${CLIENT_1_PORT}
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:      
      - "${CLIENT_1_PORT}:${CLIENT_1_PORT}"

  client2:
    build:
      context: ./Client
      args:
        OPEN_PORT: ${CLIENT_2_PORT}
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:      
      - "${CLIENT_2_PORT}:${CLIENT_2_PORT}"

  server:
    build:
      context: ./Server
      args:
        OPEN_PORT: ${SERVER_PORT}
    restart: always
    environment:
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: SuperTajneHaslo
      MYSQL_DATABASE_DB: DB
      MYSQL_DATABASE_HOST: DB
      MYSQL_DATABASE_PORT: ${DB_PORT}
    ports: ["${SERVER_PORT}:${SERVER_PORT}"]
    depends_on:
      - mysql
    volumes:
        - key:/key/


volumes:
    key:
        external: false


